sendinel/medicines/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns("",
    url(r"^register/$",
        'sendinel.medicines.views.register', 
        name = 'medicines_register'),     
    url(r'^register/save/(?P<medicine_id>\d+)/$',
        'sendinel.medicines.views.register_save',
        name = 'medicines_register_save'),
    url(r'^send-message/$',
        'sendinel.medicines.views.send_message',
        name = 'medicines_send_message'),
    url(r'^create/$',
        'sendinel.medicines.views.create_medicine',
        name = 'medicines_create')
)

sendinel/urls.py
from django.conf.urls.defaults import handler404, handler500, include, \
                                        patterns, url
from django.conf import settings
from django.views.generic.simple import redirect_to

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

js_info_web = {
    'packages': ('sendinel')
}

urlpatterns = patterns('',
    url(r'^$', redirect_to, {'url': 'web/'}),
    (r'^groups/', include('sendinel.groups.urls')),
    (r'^infoservices/', include('sendinel.infoservices.urls')),
    (r'^medicine/', include('sendinel.medicines.urls')),
    (r'^web/', include('sendinel.web.urls')),
    (r'^notifications/', include('sendinel.notifications.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', 'django.views.i18n.javascript_catalog', js_info_web,
        name = "jsi18n"),
    # (r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)), 
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^mediaweb/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
        (r'^admin_media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

sendinel/infoservices/models.py
from string import Template

from django.db import models
from django.utils.translation import ugettext_lazy

from sendinel.backend import texthelper
from sendinel.backend.models import Patient, \
                                    Sendable, \
                                    WayOfCommunication
from sendinel.backend.output import SMSOutputData, \
                                    VoiceOutputData


class InfoService(models.Model):
    """
    Represent a user group.
    Existing types are 'information' and 'medicine' 
    whereas information-groups send regular messages to their 
    subscribers, medicine deletes the group after sending a message
    """
    
    TYPES = (
        ('information', ugettext_lazy("Information Group")),
        ('medicine', ugettext_lazy('Waiting List for Medicine'))
    )
    TYPE_TEXTS = {
        'information': {
            'title': ugettext_lazy('Information Groups'),
            'name': ugettext_lazy('information group'),
            'members_button': ugettext_lazy('Group members'),
            'remove_button': ugettext_lazy('Remove group'),
            'remove_patient_button': ugettext_lazy('Remove patient from group'),
            'form_field_description': ugettext_lazy('Inform patients about:'),
            'table_head': ugettext_lazy('Information')
        },
        'medicine': {
            'title': ugettext_lazy('Waiting Lists for Medicine'),
            'name': ugettext_lazy('waiting list for medicine'),
            'members_button': ugettext_lazy('List members'),
            'remove_button': ugettext_lazy('Remove list'),
            'remove_patient_button': ugettext_lazy('Remove patient from list'),
            'form_field_description':
            ugettext_lazy('The patients are waiting for the following medicine:'),
            'table_head': ugettext_lazy('Medicine')
        },
    }
    
    
    members = models.ManyToManyField(Patient, through = "Subscription")
    name = models.CharField(max_length = 255,
                            default = None,
                            unique = True,
                            blank = False,
                            null = False,
                            verbose_name = ugettext_lazy("name"))
    type = models.CharField(max_length = 255, 
                            choices = TYPES,
                            default = None,
                            blank = False, 
                            null = False)
    
    class Meta:
        verbose_name = ugettext_lazy("Information service")
                            
    def __unicode__(self):
        return self.name
    
    def member_count(self):
        return self.members.all().count()
    
    def texts(self):
        """
        Returns the text blocks associated with the group's type.
        """
        return self.TYPE_TEXTS[self.type]


class InfoMessage(Sendable):
    """
    Define a InfoMessage.
    """

    template = Template("$text")
    text = models.TextField()
    
    def __unicode__(self):
        return "InfoMessage to %s: '%s' via %s" % \
                                        (self.recipient.phone_number,
                                         self.text,
                                         self.way_of_communication)
    
    def get_data_for_sms(self):
        """
        Prepare OutputData for sms.
        Generate the message for an InfoMessage.
        Return SMSOutputData for sending.
        """
        
        data = SMSOutputData()           
        data.data = texthelper.generate_text({'text': self.text},
                                             InfoMessage.template)
        data.phone_number = self.recipient.phone_number
                
        return data
        
    def get_data_for_voice(self):
        """
        Prepare OutputData for voicecall.
        Generate the message for an InfoMessage.
        Return VoiceOutputData for sending.
        """
        
        data = VoiceOutputData()
        data.data = self.text
        data.phone_number = self.recipient.phone_number
            
        return data


class Subscription(models.Model):
    """
    Represents a patient's subscription to an infoservice
    """

    patient = models.ForeignKey(Patient)
    infoservice = models.ForeignKey(InfoService)

    way_of_communication = models.ForeignKey(WayOfCommunication)

    def __unicode__(self):
        return "%s %s" % (unicode(self.infoservice), \
                          unicode(self.patient.phone_number))

sendinel/medicine/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from sendinel.backend.models import Hospital
from sendinel.backend.authhelper import redirect_to_authentication_or
from sendinel.infoservices.models import InfoService
from sendinel.groups.forms import MedicineMessageValidationForm, \
                                  RegisterPatientForMedicineForm
from sendinel.infoservices.utils import create_messages_for_infoservice, \
                                        set_session_variables_for_register, \
                                        subscription_save
from sendinel.logger import logger, log_request
from sendinel.settings import AUTH_NUMBER, MEDICINE_MESSAGE_TEMPLATE
from sendinel.web.utils import fill_authentication_session_variable, \
                               render_status, \
                               get_ways_of_communication



@log_request
def register_save(request, medicine_id):

    subscription = subscription_save(request, medicine_id)
    
    backurl = reverse('medicine_register')        
    nexturl = reverse('web_index')
    title = _("Registration successful")
    message = _("The patient will receive a messages once the medicine "
                " \"%s\" is available in the clinic again.") \
                % subscription.infoservice.name
    
    return render_status(request, True, title, message, backurl, nexturl)

@log_request                              
def register(request):
    '''
    Register a patient to the waitinglist of a medicine, i.e.
    a new subscription if the infoservice is created.
    '''
    ajax_url= reverse('web_check_call_received')
    medicines = InfoService.objects.all().filter(type='medicine')
    
    ways_of_communication = get_ways_of_communication(immediate = True)
    
    if request.method == "POST":
        set_session_variables_for_register(request)
        request.session['medicine'] = request.POST.get('medicine', '')
        
        form = RegisterPatientForMedicineForm(request.POST)
        
        if form.is_valid():
            number = fill_authentication_session_variable(request) 
            auth_number = AUTH_NUMBER
            backurl = reverse('web_index')

            return redirect_to_authentication_or(
                            reverse('medicine_register_save',
                                 kwargs = {'medicine_id': 
                                            request.session['medicine']}))
        else:
            logger.info("register patient for medicine: Invalid form.")
       
    backurl = reverse("web_index")
    
    return render_to_response('medicine/register.html', 
                              locals(),
                              context_instance = RequestContext(request))

                              
@log_request
def send_message(request):
    '''
        Display the form and send a message to all 
        patients waiting for the medicine. 
        Afterwards, the medicine information group is deleted.
    '''
    if request.method == 'POST':
        form = MedicineMessageValidationForm(request.POST)
        
        if form.is_valid():
            med_id = form.cleaned_data['medicine'].pk
            medicine = get_object_or_404(InfoService, pk = med_id)
            create_messages_for_infoservice(medicine, form.cleaned_data['text'])
                
            medicine.delete()
            
            nexturl = reverse('web_index')
            title = _("Message created")
            message = _("All patients who were waiting for the medicine " +
                        "\"%s\" will be informed") % medicine.name

            return render_status(request, True, title, message, nexturl = nexturl)
                                      
    medicines = InfoService.objects.all().filter(type='medicine')
    
    current_hospital = Hospital.objects.all().filter(current_hospital = True)[0]
    template_text = MEDICINE_MESSAGE_TEMPLATE
    template_text = template_text.replace("$hospital", current_hospital.name)
    return render_to_response('medicine/message_create.html',
                              locals(),
                              context_instance = RequestContext(request))

sendinel/medicines/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.utils import simplejson
from django.utils.translation import ugettext as _

from sendinel.backend.models import Hospital
from sendinel.backend.authhelper import redirect_to_authentication_or
from sendinel.infoservices.forms import InfoServiceValidationForm 
from sendinel.infoservices.models import InfoService
from sendinel.infoservices.utils import create_messages_for_infoservice, \
                                        set_session_variables_for_register, \
                                        subscription_save
from sendinel.logger import logger, log_request
from sendinel.medicines.forms import MedicineMessageValidationForm, \
                                     RegisterPatientForMedicineForm
from sendinel.settings import AUTH_NUMBER, MEDICINE_MESSAGE_TEMPLATE
from sendinel.web.utils import fill_authentication_session_variable, \
                               get_ways_of_communication



@log_request
def register_save(request, medicine_id):
    '''
        Save the subscription of the patient to the medicine waiting list.
        Display the success message.
    '''
    subscription = subscription_save(request, medicine_id)
    
    backurl = reverse('medicines_register')        
    nexturl = reverse('web_index')
    title = _("Registration successful")
    message = _("The patient will receive a message once the medicine "
                " \"%s\" is available in the clinic again.") \
                % subscription.infoservice.name
    new_button_label = _("Register another patient")
    success = True
    
    return render_to_response('web/status_message.html', 
                          locals(),
                          context_instance = RequestContext(request))

@log_request                              
def register(request):
    '''
    Register a patient to the waitinglist of a medicine, i.e.
    a new subscription of the infoservice is created.
    '''
    ajax_url= reverse('web_check_call_received')
    medicines = InfoService.objects.all().filter(type='medicine')
    
    ways_of_communication = get_ways_of_communication(immediate = True)
    
    if request.method == "POST":
        set_session_variables_for_register(request)
        
        infoservice = None
        form = None

        form = RegisterPatientForMedicineForm(request.POST)
        request.session['medicine'] = request.POST.get('medicine', '')
                
        if form.is_valid():
            number = fill_authentication_session_variable(request) 
            auth_number = AUTH_NUMBER
            backurl = reverse('web_index')

            return redirect_to_authentication_or(
                            reverse('medicines_register_save',
                                 kwargs = {'medicine_id': 
                                            request.session['medicine']}))
        else:
            logger.info("register patient for medicine: Invalid form.")
       
    backurl = reverse("web_index")
    
    return render_to_response('medicine/register.html', 
                              locals(),
                              context_instance = RequestContext(request))

def create_medicine(request):
    data = {'name': request.POST['name'],
            'type': 'medicine'}
    form = InfoServiceValidationForm(data)
    
    response = {}
    if form.is_valid():
        form.save()
        infoservice = form.instance
        response['id'] = infoservice.id
        response['name'] = infoservice.name
    else:
        response['errors'] = form.errors
    
    return HttpResponse(content = simplejson.dumps(response),
                        content_type = "application/json")

@log_request
def send_message(request):
    '''
        Display the form and send a message to all 
        patients waiting for the medicine. 
        Afterwards, the medicine information group is deleted.
    '''
    if request.method == 'POST':
        form = MedicineMessageValidationForm(request.POST)
        
        if form.is_valid():
            med_id = form.cleaned_data['medicine'].pk
            medicine = get_object_or_404(InfoService, pk = med_id)
            create_messages_for_infoservice(medicine, form.cleaned_data['text'])
                
            medicine.delete()
            
            backurl = reverse('medicines_send_message')
            nexturl = reverse('web_index')
            title = _("Message created")
            message = _("All patients who were waiting for the medicine "
                        "\"%s\" will be informed. The waiting list"
                        " will also be removed.") % medicine.name
            new_button_label = _("Send another message")
            success = True

            return render_to_response('web/status_message.html', 
                          locals(),
                          context_instance = RequestContext(request))
                                      
    medicines = []
    for medicine in InfoService.objects.all().filter(type='medicine'):
        if medicine.members.count() > 0:
            medicines.append(medicine)
    
    current_hospital = Hospital.get_current_hospital()
    template_text = MEDICINE_MESSAGE_TEMPLATE
    template_text = template_text.replace("$hospital", current_hospital.name)
    return render_to_response('medicine/message_create.html',
                              locals(),
                              context_instance = RequestContext(request))

sendinel/templates/medicine/medicine_register.html
{% extends "base.html" %}
{% load i18n %}

{% block script %}
    <script src="{{ MEDIA_URL }}/js/phone_input_validation.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ MEDIA_URL }}/js/way_of_communication.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ MEDIA_URL }}/js/jVal.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jval/jVal.css">
{% endblock %}
 
{% block content %}

    <div id="contentform">
        <h3>{% trans "Register patient for Waiting List for Medicine" %}</h3>
    	<p>{% trans "Please enter the patient's phone number and the way the patient wants to receive the notification." %}</p>
        <p>{% trans "Then choose the medicine the patient is waiting for." %}</p>        
        <br />
        <form name="infoservice" method="post" class="selectable_container" action='#' autocomplete="off">

            <div class="button button-left background-grey link menu-hover rounded-corners float-left" onClick="javascript:location.href='{{ backurl }}'">
                {% trans "Back" %}
            </div>
            <div class="field field-groups float-left">
                {% include "utils/phone_number_widget.html" %}
            </div>

            <div class="field field-groups float-left ">
                {% include "utils/way_of_communication_widget.html" %}
            </div>
            <div class="field field-groups float-left lastfield">
                {% include "utils/medicine_widget.html" %}
            </div>
            <div class="button button-right link menu-hover background-grey rounded-corners float-left" onClick="infoservice.submit();">{% trans "Next" %}</div>
            <div style="clear:both;"></div>
        </form>    
    </div>

{% endblock %}

sendinel/templates/medicine/message_create.html
{% extends "base.html" %}
{% load i18n %}

{% block script %}

    <script src="{{ MEDIA_URL }}/js/infomessage.js" type="text/javascript"></script>
    <script src="{{ MEDIA_URL }}/js/validate_sms_input.js" type="text/javascript"></script>
    <script src="{{ MEDIA_URL }}/js/jVal.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jval/jVal.css">
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_text").val("{{ template_text }}")
            $("#id_text").keyup();
        });
    </script>
{% endblock %}

{% block content %}

    <div id="contentform">
        <h3>{% trans "Inform about the Arrival of Medicine " %} </h3>
            <form name="infoservice" id="content_form" action="" method="post">
            <br />
                <div class="button button-left float-left background-grey link menu-hover rounded-corners" onClick="javascript:location.href='{% url web_index %}'">
                    {% trans "Back" %}
                </div>
                <div class="field float-left">
                    {% include "utils/medicine_widget.html" %}
                </div>
                <div class="field float-left lastfield">
                    {% include "utils/enter_message_widget.html" %}
                </div>
            
                <div class="button button-right link menu-hover background-grey float-left rounded-corners" onClick="infoservice.submit();">{% trans "Next" %}</div>
                <div style="clear:both;"></div>
            
            </form>

        <br />

     </div>

{% endblock %}

sendinel/templates/medicine/register.html
{% extends "base.html" %}
{% load i18n %}

{% block script %}
    <script src="{{ MEDIA_URL }}/js/add_new_medicine.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ MEDIA_URL }}/js/phone_input_validation.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ MEDIA_URL }}/js/way_of_communication.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ MEDIA_URL }}/js/jVal.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jval/jVal.css">
    <script type="text/javascript">
        var medicines_create_url = '{% url medicines_create %}';
    </script>
{% endblock %}
 
{% block content %}

    <div id="contentform">
        <h3>{% trans "Register patient for Waiting List for Medicine" %}</h3>
    	<p>{% trans "Please enter the patient's phone number and the way the patient wants to receive the notification." %}</p>
        <p>{% trans "Then choose the medicine the patient is waiting for." %}</p>        
        <br />
        <form name="infoservice" method="post" id="content_form" action='#' autocomplete="off">

            <div class="button button-left background-grey link menu-hover rounded-corners float-left" onClick="javascript:location.href='{{ backurl }}'">
                {% trans "Back" %}
            </div>
            <div class="field field-groups float-left">
                {% include "utils/phone_number_widget.html" %}
            </div>

            <div class="field field-groups float-left ">
                {% include "utils/way_of_communication_widget.html" %}
            </div>
            <div class="field field-groups float-left lastfield">
                {% include "utils/medicine_widget.html" %}
                <br />
                <div id="infoservice-create">
                    <img src="{{ MEDIA_URL }}/img/add.png" style="margin-bottom:-8px" />
                    <input id="medicines_create_button" type="button" 
                            value='{% trans "Add a new medicine" %}' />
                </div>
            </div>
                                    
            <div class="button button-right link menu-hover background-grey rounded-corners float-left" onClick="infoservice.submit();">{% trans "Next" %}</div>
            <div style="clear:both;"></div>
        </form>
        
        <div id="dialog-form" style="display: none">
            <p class="centered">{% trans "Please enter the name of the medicine you want to add" %}</p>
            
            <form>
                <br />
                <div class="errorlist" style="display:none"></div>
                <br />
                <input type="text" name="name" id="medicine_input" size="10"/>
            </form>
        </div>
        
    </div>

{% endblock %}